package com.zack.linerelay.db;

import java.time.Instant;

/**
 * Structured stock signal generated by the upstream collector from a market
 * analysis row.
 */
public record TradeSignal(
        long id,
        long analysisId,
        String analysisDate,
        String analysisSlot,
        String market,
        String ticker,
        String name,
        String signalType,
        String strategyType,
        String direction,
        String confidence,
        String entryZone,
        String invalidation,
        String takeProfitZone,
        String holdingHorizon,
        String rationale,
        String riskNotes,
        String status,
        String rawJson,
        String analysisModel,
        String analysisPromptVersion,
        String analysisSummaryText,
        String analysisRawJson,
        String analysisStructuredJson,
        Instant updatedAt
) {}
