CREATE TABLE IF NOT EXISTS t_market_analyses (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  analysis_date VARCHAR(32) NOT NULL,
  analysis_slot VARCHAR(64) NOT NULL,
  scheduled_time_local VARCHAR(64),
  model VARCHAR(64),
  prompt_version VARCHAR(64),
  summary_text CLOB,
  raw_json CLOB,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_bot_group_info (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  group_id VARCHAR(128) NOT NULL,
  test_account TINYINT DEFAULT 0,
  active TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_bot_user_info (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(128) NOT NULL,
  test_account TINYINT DEFAULT 0,
  active TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
